nome = str(input('Digite seu nome completo: ')).strip()
print('Analisando seu nome...')
nome = nome.upper()
print(f'Em maiusculas deu nome fica assim {nome}')
nome = nome.lower()
print(f'E em minusculas assim {nome}')
nomelen = len(nome) - nome.count(' ')
print(f'O seu nome possui {nomelen} letras')
separa = nome.split()
separalen = len(separa[0])
print(f'O seu primeiro nome é {separa[0]} e tem {separalen} letras')