pvalor = float(input('Digite o primeiro valor: '))
svalor = float(input('Digite o segundo valor: '))
tvalor = float(input('Digite o terceiro valor: '))
print(f'O maior valor foi {max(pvalor, svalor, tvalor):.0f}')
print(f'O menor valor foi {min(pvalor, svalor, tvalor):.0f}')