algo = input('digite algo: ')
ty = type(algo)
space = algo.isspace()
num = algo.isnumeric()
alfab = algo.isalpha()
alfanum = algo.isalnum()
maiusc = algo.isupper()
minusc = algo.islower()
capit = algo.istitle()

print(f'o tipo primitivo de {algo} é {ty}')
print(f'ele só tem espaços? {space}')
print(f'ele é um numero? {num}')
print(f'ele é alfabetico? {alfab}')
print(f'ele é alfanumerico? {alfanum}')
print(f'ele está em maiusculas? {maiusc}')
print(f'ele está em minusculas? {minusc}')
print(f'ela está capitalizada? {capit}')